---
title: "<span style='font-family: times, Open Sans'>Project</style>"
output: 
  html_document:
    css: CSSBackgrounds15.css
---

<style>
body {
text-align: justify}
</style>

<p style="font-family: times, Open Sans; font-size:14pt">
**Rockwall slope erosion of mountain catchment headwaters and periglacial landscape change in the NW Himalaya (Collaborative)–status: completed (2015–2019)** 
</p>
<p style="font-family: times, Open Sans; font-size:12.5pt">
This project explored rockwall slope erosion's contribution to the denudation budgets of glacierized alpine catchments in the NW Himalaya. We quantified the upper glacial catchment's erosion rate in eleven glaciated valleys using $^{10}$Be concentration in supraglacial sediment. We also tried to resolve the drivers of rockwall slope erosion by comparing catchment headwaters' erosion across gradients in lithology, topography, rock uplift, and climate in the northwestern. Our findings show that tectonically driven uplift has moderated the pace of landscape evolution since the formation of the orogen. We also explored the evolution of periglacial fans in the NW Himalaya using $^{10}$Be on fan surface boulders under this project. Our results show that fan surface abandonment coincides with periods of cooling and weakening monsoon strength, and local and regional glacier advances.
</p>
<p style="font-family: times, Open Sans; font-size:12.5pt">
*Collaborators*: [Lewis A. Owen (PI)](https://meas.sciences.ncsu.edu/people/laowen2/), NCSU; [Elizabeth N. Orr (Graduate student)](https://www.elizabethorr.co.uk/), University of Bristol; [Mark W. Caffee (Collaborator)](http://www.physics.purdue.edu/people/faculty/mcaffee.php), PU.
</p>
<p style="font-family: times, Open Sans; font-size:12.5pt">
*Funding Agency*: [Geological Society of America (GSA)](https://www.geosociety.org/GSA/Education_Careers/Grants_Scholarships/Research_Grants/GSA/grants/gradgrants.aspx), [PRIME laboratories, Purdue University](https://www.physics.purdue.edu/primelab/user-information/freeseedanalysis.php), [Graduate Student Governance Association (GSGA) at the University of Cincinnati](https://grad.uc.edu/student-life/awards/gsga-awards.html), NSF (awarded to MWC).
</p>
<p style="font-family: times, Open Sans; font-size:12.5pt">
*Publications*: [Orr et al. 2020a](files/Orr_et_al.2020b.pdf), [Orr et al. 2020b](files/Orr_et_al.2020.pdf)), [Orr et al. 2019](files/Orr_et_al.2019.pdf).
</p>
<br>

<p style="font-family: times, Open Sans; font-size:12.5pt">
*Feel free to get in touch*
</p> 
<p style="font-family: times, Open Sans; font-size:14pt">
[**Contact me**](Contactme.html)
</p>
