---
title: "<span style='font-family: times, Open Sans'>Publications</style>"
output: 
  html_document:
    css: CSSBackgrounds9.css
---

<style>
body {
text-align: justify}
</style>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<p style="font-family: times, Open Sans; font-size:14pt">
**Peer-reviewed Publications**
</p>

<p style="font-family: times, Open Sans; font-size:12.5pt">
**Saha, S.**, Moon, S., Brown, N.D., Rhodes, Scharer, K.M., McPhillips, D., McGill, S. F., and Castillo, B. A. Holocene depositional history inferred from single-grain luminescence ages in southern California, North America. *Geophysical Research Letter, in review.*
</p>

<p style="font-family: times, Open Sans; font-size:12.5pt">
Dortch, J.M., Tomkins, M., **Saha, S.**, Schoenbohm, L., Murari, M.K., and Curl, D. Probability-based interpretation of terrestrial cosmogenic radionuclide ages: P-CAAT, a tool for the ages. *Geochronology, in review.*
</p>

<p style="font-family: times, Open Sans; font-size:12.5pt">
Orr, E.N., Owen, L.A., **Saha, S.**, Hammer, S., and Caffee, M.W. 2020. Rockwall slope erosion in the NW Himalaya. *Journal of Geophysical Research - Earth Surface, preprint. https://doi.org/10.1002/essoar.10502583.2*
</p>

<p style="font-family: times, Open Sans; font-size:12.5pt">
Orr, E.N., Owen, L.A., **Saha, S.**, Hammer, S., and Caffee, M.W. 2020. "Climate-driven late Quaternary fan surface abandonment in the NW Himalaya," Untangling the Quaternary Period—A Legacy of Stephen
C. Porter. Ed: Waitt, R.B., Thackray, G.D., Gillespie, A.R., *Geological Society of America Special Paper. https://doi.org/10.1130/2020.2548(04)*
</p>

<p style="font-family: times, Open Sans; font-size:12.5pt">
**Saha, S.**, Owen, L.A., Orr, E.N., and Caffee, M.W. 2020. A statistical and numerical modeling approach for spatiotemporal reconstruction of glaciations in the Central Asian mountains. *MethodsX 220, 372–400. https://doi.org/10.1016/j.mex.2020.100820*
</p>

<p style="font-family: times, Open Sans; font-size:12.5pt">
Orr, E.N., Owen, L.A., **Saha, S.**, and Caffee, M.W. 2019. Rates of rockwall slope erosion in the upper Bhagirathi catchment, Garhwal Himalaya. *Earth Surface Processes and Landforms 44, 3108–3127. https://doi.org/10.1002/esp.4720*
</p>

<p style="font-family: times, Open Sans; font-size:12.5pt">
**Saha, S.**, Owen, L.A., Orr, E.N., and Caffee, M.W. 2019. Cosmogenic $^{10}$Be and equilibrium-line altitude dataset of Holocene glacier advances in the Himalayan-Tibetan orogen. *Data in brief 26, 104412. https://doi.org/10.1016/j.dib.2019.104412*
</p>

<p style="font-family: times, Open Sans; font-size:12.5pt">
**Saha, S.**, Owen, L.A., Orr, E.N., and Caffee, M.W. 2019. High-frequency Holocene glacier fluctuations in the Himalayan-Tibetan orogen. *Quaternary Science Reviews 220, 372–400. https://doi.org/10.1016/j.quascirev.2019.07.021*
</p>

<p style="font-family: times, Open Sans; font-size:12.5pt">
**Saha, S.**, Owen, L.A., Orr, E.N., and Caffee, M.W. 2018. The timing and nature of Holocene glacier advances at the northwestern end of the Himalayan-Tibetan orogen. *Quaternary Science Reviews 187. 177–202. https://doi.org/10.1016/j.quascirev.2018.03.009*
</p>

<p style="font-family: times, Open Sans; font-size:12.5pt">
Orr, E.N., Owen, L.A., **Saha, S.**, Caffee, M.W., and Murari. M.K. 2018. Quaternary glaciation of the Lato Massif, Zanskar Range of the NW Himalaya. *Quaternary Science Reviews 183. 140–156. https://doi.org/10.1016/j.quascirev.2018.01.005*
</p>

<p style="font-family: times, Open Sans; font-size:12.5pt">
Orr, E.N., Owen, L.A., Murari, M.K., **Saha, S.**, and Caffee, M.W. 2017. Quaternary glaciation of Stok, northern Zanskar Range, Transhimalaya, Northern India. *Geomorphology 284. 142–155. https://doi.org/10.1016/j.geomorph.2016.05.031*
</p>

<p style="font-family: times, Open Sans; font-size:12.5pt">
**Saha, S.**, Sharma, M.C., Murari, M.K., Owen, L.A., and Caffee, M.W. 2016. Geomorphology, sedimentology, and minimum exposure ages of streamlined subglacial landforms in the NW Himalaya, India. *Boreas 45, 284–303. https://doi.org/10.1111/bor.12153*
</p>

<br>

<p style="font-family: times, Open Sans; font-size:14pt">
**Other Publications**
</p>

<p style="font-family: times, Open Sans; font-size:12.5pt">
**Saha. S.** 2013. Water Quality Assessment of Four Different Wetlands and its implication to Climate Change. *International Indexed & Referred Research Journal, ISSN 0975-3486, IV (40), 33–37. DOI: 10.13140/RG.2.1.3180.0401*
</p>

<br>

<p style="font-family: times, Open Sans; font-size:14pt">
**Manuscripts/Books in Preparation**
</p>

<p style="font-family: times, Open Sans; font-size:12.5pt">
**Saha, S.**, Owen, L.A., Orr, E.N., and Caffee, M.W. The role of inherited cosmogenic $^{10}$Be in the new Late Holocene moraine chronostratigraphy in the Bhagirathi catchment of the Garhwal Himalaya, northern India. *Intend to submit to GSA Bulletin, in prep.*
</p>
<p style="font-family: times, Open Sans; font-size:12.5pt">
Owen, L.A., **Saha, S.**, and Dortch, J.M. Quaternary glaciations of the Himalayan-Tibetan orogen. *Invited publication to Quaternary Science Reviews, in prep.*
</p>
<p style="font-family: times, Open Sans; font-size:12.5pt">
**Saha, S.**, Moon, S., Brown, N., and Rhodes, E. J. Quantifying the degree of pedoturbation in upstream fans using single-grain luminescence dating and its implications in downstream sediment routing and deposition. *Intend to submit to Journal of Geophysical Research Earth Surface, in prep.*
</p>
<p style="font-family: times, Open Sans; font-size:12.5pt">
**Saha, S.**, Moon, S., Scharer, K.M., Rockwell, T. K., and Brown, N. Constraining a long-term paleolake and paleoseismic history using deep boreholes at the ancient Lake Cahuilla, Coachella, California. *Intend to submit to Bulletin of the Seismological Society of America, in prep.*
</p>
<p style="font-family: times, Open Sans; font-size:12.5pt">
Chatterjee, U., Pradhan, B., Kumar, S., **Saha, S.**, and Zakwan, M. (Eds). Water, Land and Forest Susceptibility and Sustainability: Geospatial Approaches & Modeling. *It will be published in Elsevier, in prep.*
</p>

<br>

<p style="font-family: times, Open Sans; font-size:14pt">
**Published Abstracts**
</p>
<p style="font-family: times, Open Sans; font-size:14pt">
[Click here](PubAbstracts.html)
</p>

<br>
<p style="font-family: times, Open Sans; font-size:12.5pt">
*Feel free to get in touch*
</p> 
<p style="font-family: times, Open Sans; font-size:14pt">
[**Contact me**](Contactme.html)
</p>